main_deck:
  - <<: *bang
    signs:
      - 6 hearts
      - 2 clubs
      - 2 diamonds
      - 3 diamonds
    image: 17_bang
  - name: CARAVAN
    signs:
      - 2 spades
    image: 17_carovana
    color: brown
    effects:
      - pay_cube select_cubes_repeat(2)
      - caravan
      - changewws
  - <<: *cat_balou
    signs:
      - 3 hearts
    image: 17_catbalou
  - name: A_LITTLE_NIP
    signs:
      - 5 hearts
    image: 17_cicchetto
    color: brown
    effects:
      - pay_cube select_cubes_repeat(3)
      - a_little_nip
  - name: QUICK_SHOT
    signs:
      - 3 spades
    image: 17_colporapido
    color: brown
    effects:
      - pay_cube select_cubes_repeat(1)
      - bang player_per_cube reachable notself
    tags:
      - skip_logs
  - name: FLINTLOCK
    signs:
      - A spades
    image: 17_flintlock
    color: brown
    effects:
      - none player reachable notself
    optional:
      - pay_cube select_cubes(2)
    mth_effect: flintlock(0,1)
    tags:
      - skip_logs
  - name: ARROW
    signs:
      - 5 diamonds
    image: 17_freccia
    color: brown
    effects:
      - pay_cube select_cubes_repeat(1)
      - indians player_per_cube notself
    tags:
      - indians
      - skip_logs
  - name: DUCK
    signs:
      - 3 diamonds
    image: 17_giulatesta
    color: brown
    responses:
      - missed
    optional:
      - pay_cube select_cubes(2)
    mth_response: duck(1)
  - <<: *missed
    signs:
      - K spades
    image: 17_mancato
  - name: RELOAD
    signs:
      - 4 diamonds
    image: 17_ricarica
    color: brown
    effects:
      - add_cube(3)
  - name: RUST
    signs:
      - 9 spades
    image: 17_ruggine
    color: brown
    effects:
      - rust players notself not_empty_cubes
  - name: SQUAW
    signs:
      - 3 diamonds
    image: 17_squaw
    color: brown
    effects:
      - none card | table
    optional:
      - pay_cube select_cubes(2)
    mth_effect: squaw(0,1)
    tags:
      - skip_logs
  - name: ACE_UP_THE_SLEEVE
    signs:
      - A hearts
    image: 17_assonellamanica
    color: orange
    effects:
      - pay_cube self_cubes(2)
      - draw
  - name: BANDOLIER
    signs:
      - 2 hearts
    image: 17_bandoliera
    color: orange
    modifier: bandolier
    effects:
      - max_usages(1)
      - pay_cube self_cubes(1)
  - name: BIG_FIFTY
    signs:
      - Q spades
    image: 17_bigfifty
    color: orange
    modifier: bigfifty
    equip:
      - weapon(6)
    effects:
      - pay_cube self_cubes(1)
      - bigfifty
    tags:
      - weapon
  - name: BOMB
    signs:
      - 7 diamonds
    image: 17_bomba
    color: orange
    equip_target: any
    equip:
      - predraw_check(0)
      - bomb
    responses:
      - move_bomb player
    tags:
      - auto_select
  - name: BUNTLINE_SPECIAL
    signs:
      - J spades
    image: 17_buntlinespecial
    color: orange
    modifier: bangmod
    equip:
      - weapon(2)
    effects:
      - pay_cube self_cubes(1)
      - buntlinespecial
    tags:
      - weapon
  - name: BELL_TOWER
    signs:
      - 7 clubs
    image: 17_campanile
    color: orange
    modifier: belltower
    effects:
      - pay_cube self_cubes(1)
  - name: CRATE
    signs:
      - 3 hearts
    image: 17_cassa
    color: orange
    responses:
      - pay_cube self_cubes(2)
      - missed
  - name: TUMBLEWEED
    signs:
      - 4 clubs
    image: 17_cespuglio
    color: orange
    equip:
      - tumbleweed
    responses:
      - pay_cube self_cubes(1)
      - tumbleweed
  - name: DOUBLE_BARREL
    signs:
      - 6 clubs
    image: 17_doppiacanna
    color: orange
    modifier: doublebarrel
    equip:
      - weapon(1)
    effects:
      - pay_cube self_cubes(1)
      - doublebarrel
    tags:
      - weapon
  - name: WHIP
    signs:
      - 5 clubs
    image: 17_frusta
    color: orange
    effects:
      - pay_cube self_cubes(3)
      - destroy card | table
    tags:
      - skip_logs
  - name: BEER_KEG
    signs:
      - 4 hearts
    image: 17_fustodibirra
    color: orange
    effects:
      - pay_cube self_cubes(3)
      - heal
  - name: LOCKPICK
    signs:
      - 2 clubs
    image: 17_grimaldello
    color: orange
    effects:
      - pay_cube self_cubes(3)
      - steal card notself | hand
    tags:
      - skip_logs
  - name: THUNDERER
    signs:
      - 3 clubs
    image: 17_thunderer
    color: orange
    modifier: bangmod
    equip:
      - weapon(3)
    effects:
      - pay_cube self_cubes(1)
      - thunderer
    tags:
      - weapon

character:
  - name: AL_PREACHER
    image: 17_alpreacher
    equip:
      - al_preacher
    responses:
      - al_preacher
    optional:
      - pay_cube select_cubes(2)
      - draw
    tags:
      - auto_select
  - name: BASS_GREEVES
    image: 17_bassgreeves
    effects:
      - max_usages(1)
      - discard card self | hand
      - add_cube(2) card self | cube_slot can_target_self
  - name: BLOODY_MARY
    image: 17_bloodymary
    equip:
      - bloody_mary
  - name: FRANKIE_CANTON
    image: 17_frankiecanton
    effects:
      - max_usages(1)
      - frankie_canton card | cube_slot
  - name: JULIE_CUTTER
    image: 17_juliecutter
    equip:
      - julie_cutter
  - name: MEXICALI_KID
    image: 17_mexicalikid
    effects:
      - max_usages(1)
      - pay_cube select_cubes(2)
      - bang player reachable notself
    tags:
      - skip_logs
  - name: MS_ABIGAIL
    image: 17_msabigail
    equip:
      - ms_abigail
    responses:
      - ms_abigail
  - name: RED_RINGO
    image: 17_redringo
    equip:
      - red_ringo
    effects:
      - max_usages(1)
      - red_ringo move_cube_slot(2) self | cube_slot table
    tags:
      - max_hp(5)