main_deck:
  - <<: *barrel
    signs:
      - A clubs
    image: 03_barile
    expansion: dodgecity
  - name: BINOCULAR
    signs:
      - 10 diamonds
    image: 03_binocolo
    expansion: dodgecity
    color: blue
    equip:
      - scope
  - <<: *dynamite
    signs:
      - 10 clubs
    image: 03_dinamite
    expansion: dodgecity
  - <<: *mustang
    signs:
      - 5 hearts
    image: 03_mustang
    expansion: dodgecity
  - <<: *remington
    signs:
      - 6 diamonds
    image: 03_remington
    expansion: dodgecity
  - <<: *rev_carabine
    signs:
      - 5 spades
    image: 03_rev_carabine
    expansion: dodgecity
  - name: HIDEOUT
    signs:
      - K diamonds
    image: 03_riparo
    expansion: dodgecity
    color: blue
    equip:
      - mustang
  - <<: *bang
    signs:
      - 8 spades
      - 5 clubs
      - 6 clubs
      - K clubs
    image: 03_bang
    expansion: dodgecity
  - <<: *beer
    signs:
      - 6 hearts
      - 6 spades
    image: 03_birra
    expansion: dodgecity
  - <<: *cat_balou
    signs:
      - 8 clubs
    image: 03_cat_balou
    expansion: dodgecity
  - <<: *general_store
    signs:
      - A spades
    image: 03_emporio
    expansion: dodgecity
  - <<: *indians
    signs:
      - 5 diamonds
    image: 03_indiani
    expansion: dodgecity
  - <<: *missed
    signs:
      - 8 diamonds
    image: 03_mancato
    expansion: dodgecity
  - <<: *panic
    signs:
      - J hearts
    image: 03_panico
    expansion: dodgecity
  - name: PUNCH
    signs:
      - 10 spades
    image: 03_pugno
    expansion: dodgecity
    color: brown
    effects:
      - bang player notself range_1
    tags:
      - skip_logs
  - name: RAG_TIME
    signs:
      - 9 hearts
    image: 03_rag_time
    expansion: dodgecity
    color: brown
    effects:
      - discard extra_card self | hand
      - discard
      - steal card
    tags:
      - skip_logs
      - no_auto_discard
  - name: BRAWL
    signs:
      - J spades
    image: 03_rissa
    expansion: dodgecity
    color: brown
    effects:
      - discard extra_card self | hand
      - discard
      - destroy cards_other_players
    tags:
      - skip_logs
      - no_auto_discard
  - &dodge
    name: DODGE
    signs:
      - 7 diamonds
      - K hearts
    image: 03_schivata
    expansion: dodgecity
    color: brown
    responses:
      - missed
      - draw
  - name: SPRINGFIELD
    signs:
      - K spades
    image: 03_springfield
    expansion: dodgecity
    color: brown
    effects:
      - discard extra_card self | hand
      - discard
      - bang player notself
    tags:
      - skip_logs
      - no_auto_discard
  - name: TEQUILA
    signs:
      - 9 clubs
    image: 03_tequila
    expansion: dodgecity
    color: brown
    effects:
      - discard extra_card self | hand
      - discard
      - heal player
    tags:
      - no_auto_discard
  - name: WHISKY
    signs:
      - Q hearts
    image: 03_whisky
    expansion: dodgecity
    color: brown
    effects:
      - discard extra_card self | hand
      - discard
      - heal(2)
    tags:
      - no_auto_discard
  - name: BIBLE
    signs:
      - 10 hearts
    image: 03_bibbia
    expansion: dodgecity
    color: green
    responses:
      - missed
      - draw
  - name: CANTEEN
    signs:
      - 7 hearts
    image: 03_borraccia
    expansion: dodgecity
    color: green
    effects:
      - heal
  - name: CAN_CAN
    signs:
      - J clubs
    image: 03_can_can
    expansion: dodgecity
    color: green
    effects:
      - destroy card
    tags:
      - skip_logs
  - name: TEN_GALLON_HAT
    signs:
      - J diamonds
    image: 03_cappello
    expansion: dodgecity
    color: green
    responses:
      - missed
  - name: CONESTOGA
    signs:
      - 9 diamonds
    image: 03_conestoga
    expansion: dodgecity
    color: green
    effects:
      - steal card
    tags:
      - skip_logs
  - name: DERRINGER
    signs:
      - 7 spades
    image: 03_derringer
    expansion: dodgecity
    color: green
    effects:
      - draw
      - bang player notself range_1
    tags:
      - skip_logs
  - name: BUFFALO_RIFLE
    signs:
      - 9 clubs
    image: 03_fucile_da_caccia
    expansion: dodgecity
    color: green
    effects:
      - bang player notself
    tags:
      - skip_logs
  - name: HOWITZER
    signs:
      - 9 spades
    image: 03_howitzer
    expansion: dodgecity
    color: green
    effects:
      - bang players notself
  - name: PEPPERBOX
    signs:
      - A hearts
    image: 03_pepperbox
    expansion: dodgecity
    color: green
    effects:
      - bang player reachable notself
    tags:
      - skip_logs
  - name: IRON_PLATE
    signs:
      - A diamonds
      - Q spades
    image: 03_placca_di_ferro
    expansion: dodgecity
    color: green
    responses:
      - missed
  - name: PONY_EXPRESS
    signs:
      - Q diamonds
    image: 03_pony_express
    expansion: dodgecity
    color: green
    effects:
      - draw(3)
      - changewws
  - name: KNIFE
    signs:
      - 8 hearts
    image: 03_pugnale
    expansion: dodgecity
    color: green
    effects:
      - bang player notself range_1
    tags:
      - skip_logs
  - name: SOMBRERO
    signs:
      - 7 clubs
    image: 03_sombrero
    expansion: dodgecity
    color: green
    responses:
      - missed

character:
  - name: APACHE_KID
    image: 03_apache_kid
    expansion: dodgecity
    equip:
      - apache_kid
    tags:
      - max_hp(3)
  - name: BELLE_STAR
    image: 03_belle_star
    expansion: dodgecity
    equip:
      - bellestar
  - name: BILL_NOFACE
    image: 03_bill_noface
    expansion: dodgecity
    equip:
      - bill_noface
  - name: CHUCK_WENGAM
    image: 03_chuck_wengam
    expansion: dodgecity
    effects:
      - damage
      - queue_draw(2)
  - name: DOC_HOLYDAY
    image: 03_doc_holyday
    expansion: dodgecity
    effects:
      - max_usages(1)
      - mth_add cards(2) self | hand
      - mth_add player reachable notself
    mth_effect: doc_holyday
  - name: ELENA_FUENTE
    image: 03_elena_fuente
    expansion: dodgecity
    responses:
      - missed
      - discard card self | hand
    tags:
      - max_hp(3)
  - name: GREG_DIGGER
    image: 03_greg_digger
    expansion: dodgecity
    equip:
      - greg_digger
    tags:
      - discard_if_two_players
  - name: HERB_HUNTER
    image: 03_herb_hunter
    expansion: dodgecity
    equip:
      - herb_hunter
    tags:
      - discard_if_two_players
  - name: JOSE_DELGADO
    image: 03_jose_delgado
    expansion: dodgecity
    effects:
      - max_usages(2)
      - discard card self | hand blue
      - draw(2)
  - name: MOLLY_STARK
    image: 03_molly_stark
    expansion: dodgecity
    equip:
      - molly_stark
  - name: PAT_BRENNAN
    image: 03_pat_brennan
    expansion: dodgecity
    responses:
      - end_drawing
      - steal card | table
    tags:
      - drawing
  - name: PIXIE_PETE
    image: 03_pixie_pete
    expansion: dodgecity
    equip:
      - pixie_pete
    tags:
      - max_hp(3)
  - name: SEAN_MALLORY
    image: 03_sean_mallory
    expansion: dodgecity
    equip:
      - gunbelt(10)
    tags:
      - max_hp(3)
  - name: TEQUILA_JOE
    image: 03_tequila_joe
    expansion: dodgecity
    equip:
      - tequila_joe
  - name: VERA_CUSTER
    image: 03_vera_custer
    expansion: dodgecity
    equip:
      - predraw_check(-10)
      - vera_custer
    tags:
      - max_hp(3)