character:
  - name: CLAUS_THE_SAINT
    image: 02_clausthesaint
    equip:
      - claus_the_saint
    responses:
      - none card | selection
      - none player target_set
    mth_response: claus_the_saint(0,1)
    tags:
      - max_hp(3)
      - auto_select
  - name: JOHNNY_KISCH
    image: 02_johnnykisch
    equip:
      - johnny_kisch
  - name: UNCLE_WILL
    image: 02_unclewill
    effects:
      - max_usages(1)
      - discard card self | hand
      - generalstore
      - generalstore players
  - name: ANNIE_VERSARY
    image: 02_annieversary
    equip:
      - treat_as_bang(2)
    effects:
      - banglimit
      - set_playing card self | hand not_bangcard
      - none player reachable notself
    mth_effect: play_as_bang(1,2)
    tags:
      - play_as_bang
      - banglimit
  - name: EMILIANO
    image: 02_emiliano
    equip:
      - emiliano

highnoon:
  - name: HANDCUFFS
    image: 05_manette
    expansion: highnoon
    equip:
      - handcuffs
  - name: NEW_IDENTITY
    image: 05_nuovaidentita
    expansion: highnoon
    equip:
      - newidentity

hidden:
  - name: HANDCUFFS_HEARTS
    image: highnoon/05_manette_hearts
    expansion: highnoon
    tags:
      - handcuffs(1)
  - name: HANDCUFFS_DIAMONDS
    image: highnoon/05_manette_diamonds
    expansion: highnoon
    tags:
      - handcuffs(2)
  - name: HANDCUFFS_CLUBS
    image: highnoon/05_manette_clubs
    expansion: highnoon
    tags:
      - handcuffs(3)
  - name: HANDCUFFS_SPADES
    image: highnoon/05_manette_spades
    expansion: highnoon
    tags:
      - handcuffs(4)