bots:
  names:
  - Salvo
  - Chris
  - Lorena
  - Ismaele
  - Riccardo
  - Davide
  - Lela
  - Will
  - Sam
  - Ignazio
  - Michele
  - Jack
  - Klaus
  - Ale
  - Elisabetta

  propics:
  - bot_propics/bot_icon_1.png
  - bot_propics/bot_icon_2.png
  - bot_propics/bot_icon_3.png
  - bot_propics/bot_icon_4.png
  - bot_propics/bot_icon_5.png
  - bot_propics/bot_icon_6.png
  - bot_propics/bot_icon_7.png
  - bot_propics/bot_icon_8.png
  - bot_propics/bot_icon_9.png
  - bot_propics/bot_icon_10.png
  - bot_propics/bot_icon_11.png
  - bot_propics/bot_icon_12.png