bots:
  settings:
    allow_timer_no_action: false
    max_random_tries: 10
    bypass_prompt_after: 5
    
    response_pockets:
    - player_character
    - player_table
    - player_hand
    
    in_play_pockets:
    - player_character
    - player_table
    - player_hand
    - shop_selection
    - train
  
  names:
  - Salvo
  - Chris
  - Lorena
  - Ismaele
  - Riccardo
  - Davide
  - Lela
  - Will
  - Sam
  - Ignazio
  - Michele
  - Jack
  - Klaus
  - Ale
  - Elisabetta

  propics:
  - bot_propics/bot_icon_1.png
  - bot_propics/bot_icon_2.png
  - bot_propics/bot_icon_3.png
  - bot_propics/bot_icon_4.png
  - bot_propics/bot_icon_5.png
  - bot_propics/bot_icon_6.png
  - bot_propics/bot_icon_7.png
  - bot_propics/bot_icon_8.png
  - bot_propics/bot_icon_9.png
  - bot_propics/bot_icon_10.png
  - bot_propics/bot_icon_11.png
  - bot_propics/bot_icon_12.png