name: Build and Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  BUILD_PARALLEL_JOBS: 6
  GCC_VERSION: 13

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install packages
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt-get -y install gcc-${{env.GCC_VERSION}} g++-${{env.GCC_VERSION}} cmake ninja-build
        sudo apt-get -y install libfmt-dev libcxxopts-dev librange-v3-dev
    
    - name: Install python dependencies
      shell: bash
      run: |
        pip install pyyaml pillow

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=gcc-${{env.GCC_VERSION}}
        -DCMAKE_CXX_COMPILER=g++-${{env.GCC_VERSION}}
        -DBUILD_GAME_RELEASE=ON
        -G Ninja
      
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake --build build -j ${{ env.BUILD_PARALLEL_JOBS }} --config ${{env.BUILD_TYPE}}
    
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bangserver
        path: build/bangserver
  
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Server Artifact
      uses: actions/download-artifact@v3
      id: download
      with:
        name: bangserver
    
    - name: Run Deploy Script
      shell: bash
      run: ${{ vars.DEPLOY_SCRIPT_PATH }} ${{ steps.download.outputs.download-path }}