name: Docker Image

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install packages
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt-get -y install gcc-11 g++-11 cmake ninja-build libfmt-dev libcxxopts-dev librange-v3-dev

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=gcc-11
        -DCMAKE_CXX_COMPILER=g++-11
        -DBUILD_GAME_RELEASE=ON
        -G Ninja
      
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}