name: Docker Image

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install packages
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt-get -y install gcc-11 g++-11 cmake ninja-build libfmt-dev libcxxopts-dev librange-v3-dev

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=gcc-11
        -DCMAKE_CXX_COMPILER=g++-11
        -DBUILD_GAME_RELEASE=ON
        -G Ninja
      
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}
    
    - name: Create docker image
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        docker build -t banggameserver .
        docker run -d banggameserver